use_frameworks!

platform :ios, '9.0'

target 'YFRouter_Example' do
  pod 'YFRouter', :path => '../'
  pod 'MBProgressHUD', '~> 1.2.0'
  

  target 'YFRouter_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
  end
end
